### ISSUE TITLE
Global setup exception does not contain the TestCaseId

### ISSUE THREAD

**Issue by shaun-od** [paulegradie/Sailfish#167]
**Describe the bug**
When an exception is thrown in the lifecycle method `SailfishGlobalSetup` the exception appears in the `CompiledTestCaseResult` but without a `TestCaseId`.

**To Reproduce**
1. Run the existing Sailfish Test `GlobalSetupExceptionsAreHandled` 
2. Check the result object returned result.ExecutionSummaries[0].CompiledTestCaseResults[0].TestCaseId is null

**Expected behavior**
I would expect the test invoked when the setup method is being called that throws the exception, would be included in the returned object.

**Comment by shaun-od** [comment]
Looking at the code, I think this is because the method `CatchAndReturn` in the `SailfishExecutionEngine` creates and returns a `TestCaseExecutionResult` using the constructor that takes just the exception. 

Couldn't it create a new TestCaseExecutionResult using the preexisting constructor that allows the TestInstanceContainer and Exception to be passed in?

**Comment by paulegradie** [comment]
Thanks @shaun-od I'll address this today

**Comment by paulegradie** [comment]
> using the preexisting constructor that allows the TestInstanceContainer and Exception to be passed in
Yes - this is the way 👍
