### ISSUE TITLE
Exception from a test SailfishMethod does not contain the TestCaseId

### ISSUE THREAD

**Issue by shaun-od** [paulegradie/Sailfish#171]
**Describe the bug**
When an exception is thrown in an actual test (SailfishMethod) the exception appears in the CompiledTestCaseResult but without a TestCaseId. This is similar to #167 

**To Reproduce**
1. Run the existing Sailfish Test `OnlySailfishMethodThrows` 
2. Check the result object returned result.ExecutionSummaries[0].CompiledTestCaseResults[0].TestCaseId is null

**Expected behavior**
This use to be returned in V1.4.7. I have just upgraded to 2.0.97 and it is now null.

I do wonder if some other states are also missing the TestCaseId that shouldn't be but I haven't been able to look.

**Comment by paulegradie** [comment]
Thanks again @shaun-od 👍 I'll get this addressed and pushed out tomorrow.

**Comment by paulegradie** [comment]
An easy way to check for other scenarios with the missing testId will be to assert on that property in the existing lifecycle method tests.

I'll add that, and any missing lifecycle tests.

**Comment by paulegradie** [comment]
Addressed in https://github.com/paulegradie/Sailfish/pull/173
