### ISSUE TITLE
[docs] VS Test Framework documentation moved

### ISSUE THREAD

**Issue by BrainCrumbz** [paulegradie/Sailfish#172]
**Describe the bug**
Hi. In [TestAdapter readme](https://github.com/paulegradie/Sailfish/tree/main/source/Sailfish.TestAdapter) page there's a link to VS Test Framework documentation, but that github repo is now archived and they moved to a new one. Old link points to:

https://github.com/Microsoft/vstest-docs/blob/main/RFCs/0004-Adapter-Extensibility.md

while the new one should be:

https://github.com/microsoft/vstest/blob/main/docs/RFCs/0004-Adapter-Extensibility.md

**To Reproduce**
None

**Expected behavior**
Readme should point to new repository

**Screenshots**
None

**Desktop (please complete the following information):**
None

**Smartphone (please complete the following information):**
None

**Additional context**
None

HTH

**Comment by paulegradie** [comment]
Thanks @BrainCrumbz ! I have some updates to make to the docs generally, so I'll add this in when I push that through. I appreciate your time assembling this issue🙏

**Comment by BrainCrumbz** [comment]
Cool! Feel free to close the issue when you think is better.
